version: 1.0.0
slug: mydeconz
name: mydeCONZ
description: Control a Zigbee network with ConBee or RaspBee by Dresden Elektronik
url: https://github.com/vianneyb/hassio-addon/tree/master/mydeconz
apparmor: false
arch:
  - amd64
  - armhf
  - aarch64
backup_exclude:
  - "*/otau"
devices:
  - /dev/mem
discovery:
  - mydeconz
gpio: true
homeassistant: 0.91.2
image: homeassistant/{arch}-addon-mydeconz
ingress: true
ingress_entry: ingress.html
init: false
kernel_modules: true
options:
  device: null
panel_icon: mdi:zigbee
ports:
  40850/tcp: null
  5900/tcp: null
  8081/tcp: null
ports_description:
  40850/tcp: mydeCONZ API backend (Not required for Ingress)
  5900/tcp: mydeCONZ via VNC (Not required for Ingress. Not secure!)
  8081/tcp: mydeCONZ WebSocket (Not required for Ingress)
privileged:
  - SYS_RAWIO
schema:
  dbg_aps: int?
  dbg_info: int?
  dbg_otau: int?
  dbg_zcl: int?
  dbg_zdp: int?
  device: device(subsystem=tty)
startup: services
udev: true
usb: true
